### ISSUE TITLE
Necessary changes to Vagrantfile

### ISSUE THREAD

**Issue by jasonzoladz** [begriffs/haskell-pair#11]
Thanks for creating haskell-vim-now and haskell-pair.

I was able to get haskell-pair working but the following general changes must be made to the Vagrantfile.

1) ```provider.image``` must be ```'ubuntu-14-04-x64'```

2) ```provider.size``` must be at least ```'4GB'```, otherwise cabal will not build.

**Comment by begriffs** [comment]
Thanks for the tip! Would you care to submit a pull request for these changes?
